site_name: 机器学习速成手册
site_description: Quick Guide to Machine Learning
site_author: Demo

repo_name: demo-djh/ml-knowledge
repo_url: https://github.com/demo-djh/ml-knowledge

theme:
  name: material
  favicon: logo.png
  logo: logo.png
  

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight


  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: 切换到深色模式

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: 切换到浅色模式

  font: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
  - javascripts/glossary.js
  
plugins:
  - search
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh_CN

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - admonition
  - toc:
      permalink: true

nav:
  - 首页: index.md

  - Python:
      - 概览: Python/README.md
      - Python 安装入门: Python/下载与环境配置/README.md
      - Python 基础语法: Python/Python基础语法/README.md

  - 开发环境:
      - 概览: 开发环境/README.md
      - 编程环境部署: 开发环境/编程环境部署.md
      - Anaconda 环境配置: 开发环境/Anaconda环境配置.md

  - 数据处理:
      - 概览: 数据处理/README.md
      - 数据抓取（爬虫）: 数据处理/数据抓取.md
      - 数据基础处理: 数据处理/数据基础处理.md
      - 数据正则化: 数据处理/数据正则化.md

  - 数据可视化:
      - 概览: 数据可视化/README.md
      - 数据图表可视化: 数据可视化/数据图表可视化.md

  - 机器学习基础:
      - 概览: 机器学习基础/README.md
      - 机器学习基础名词: 机器学习基础/机器学习基础名词.md
      - 机器学习完整过程: 机器学习基础/机器学习完整过程.md

  - 机器学习算法:
      - 概览: 机器学习算法/README.md
      - 机器学习算法简介: 机器学习算法/机器学习算法简介.md
      - 机器学习算法实践: 机器学习算法/机器学习算法实践.md
      
