site_name: 机器学习速成手册
site_description: Quick Guide to Machine Learning
site_author: Demo

repo_name: demo-djh/ml-knowledge
repo_url: https://github.com/demo-djh/ml-knowledge

theme:
  name: material
  favicon: logo.png
  logo: logo.png
  

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight


  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: 切换到深色模式

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: 切换到浅色模式

  font: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
  
plugins:
  - search
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh_CN

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md


  - AI:
      - Overview: AI/README.md
      - Deep Learning: AI/Deep-Learning/README.md

  - Research:
      - Overview: Research/README.md
      
  - TEST: 
      - Overview: TEST/README.md
